#!/usr/bin/env node
// tools/build-manual.mjs — 聚合 chapters/*.md 为单一 manual.md
//
// 用法：node tools/build-manual.mjs [output-path]
// 默认输出：./manual.md
//
// 特性：
//   - 自动按 NN- 编号排序
//   - 拼接每章 frontmatter（去重）
//   - 在文首插入总目录（基于 SUMMARY.md）
//   - 处理 Markdown 锚点（## → 兼容 GitHub + Pandoc）

import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const HANDBOOK_ROOT = join(__dirname, '..');
const CHAPTERS_DIR = join(HANDBOOK_ROOT, 'chapters');
const OUTPUT = process.argv[2] || join(HANDBOOK_ROOT, 'manual.md');

function die(msg) {
  console.error(`✗ ${msg}`);
  process.exit(1);
}

function main() {
  console.log(`→ 扫描章节目录 ${CHAPTERS_DIR}`);
  const files = readdirSync(CHAPTERS_DIR)
    .filter((f) => /^\d{2}-.+\.md$/.test(f))
    .sort();
  if (files.length === 0) {
    die('没有找到 NN-*.md 章节文件');
  }
  console.log(`  找到 ${files.length} 个章节`);

  // 读 README 与 SUMMARY
  const readme = readFileSync(join(HANDBOOK_ROOT, 'README.md'), 'utf-8');
  const summary = readFileSync(join(HANDBOOK_ROOT, 'SUMMARY.md'), 'utf-8');

  // 拼装
  const parts = [];
  parts.push(`<!-- generated by tools/build-manual.mjs on ${new Date().toISOString().slice(0, 10)} -->`);
  parts.push(`<!-- 请勿手工编辑；从 chapters/*.md 重新生成 -->\n`);
  parts.push('# Ruflo 实战手册（聚合版）\n');
  parts.push('> 📘 自动从 19 个章节文件拼接。源文件在 `chapters/`，编辑源文件后 `node tools/build-manual.mjs` 重新生成。\n');
  parts.push('---\n');

  // 封面 + README 摘要
  parts.push(readme);
  parts.push('\n---\n');

  // 目录
  parts.push('# 目录\n');
  parts.push(summary);
  parts.push('\n---\n');

  // 每章
  for (const f of files) {
    const path = join(CHAPTERS_DIR, f);
    const text = readFileSync(path, 'utf-8');
    const title = basename(f, '.md');
    console.log(`  ✓ ${title}`);
    parts.push(`\n---\n\n<!-- chapter: ${title} -->\n`);
    parts.push(text);
    parts.push('\n');
  }

  // 写
  const out = parts.join('\n');
  writeFileSync(OUTPUT, out, 'utf-8');
  const lines = out.split('\n').length;
  const bytes = Buffer.byteLength(out, 'utf-8');
  console.log(`\n✓ 已生成 ${OUTPUT}`);
  console.log(`  ${lines} 行 / ${(bytes / 1024).toFixed(1)} KB`);
  console.log(`\n下一步：`);
  console.log(`  pandoc ${OUTPUT} -o ruflo-handbook.pdf --toc --toc-depth=2 -V geometry:margin=2.5cm`);
}

main();